.github/workflows/approval-comment.yaml
.github/workflows/e2e-matrix-trigger.yaml

Fixes # 
Currently for PR check-in the E2E suite is run via an approval comment directly for the e2e trigger workflow.
This works to test things, but overall has some quality of life issues, as if another approval comes in the trigger will be checked again, un-linking the previous e2e run from the PR regardless of if a new E2E suite run was requested or not.
This PR is step one of two meant to break apart the approval comment check so that the E2E suite run will not be overridden by a new review. This one added the new trigger scenario. Another follow up will be made once tested to remove the old trigger.
Not able to test since this trigger only works when in the default branch. Due to this I'm only adding the new trigger, and not removing …

test(e2e): update to add approval comment workflow for e2e trigger

---

.github/workflows/e2e-matrix-trigger.yaml

Fixes # 
Currently the ApprovalComment workflow will trigger the e2e suite even on a skipped status. We only want the workflow to be triggered on a successful run status. This PR is meant to fix it.
Sadly workflow changes need to be committed into the mainline to get executed. Will test immediately afterwards.
*
```release-note
NONE
```

test(e2e): change to have the ApprovalComment only trigger e2e suite on success

---

pkg/utils/opts/armopts.go

Fixes # 
Karpenter is a reconciler, and will retry the scale up or delete request if it fails. Also note it only retries on 429 and some other options by default. 
Instead of retrying with SDK we should retry with karpenter, and if we need additional retry flexiblity with backoff for throttling aim to get this change into karpenter core. 
Scale up scale down 
make az-presubmit 
e2etests
```release-note
```

chore(armclient): removing 429 sdk retries in favor of controller retries

---

.github/workflows/e2e-matrix-trigger.yaml

Fixes # 
Forgot to add a check for the workflow_run success of ApprovalComment within MatrixTrigger. 
This meant that runs that should have been getting skipped where failing here instead. This should fix it.
Tested on my fork, and got expected behavior:
https://github.com/charliedmcb/karpenter/actions/runs/6817129771
https://github.com/charliedmcb/karpenter/pull/2#pullrequestreview-1723448973
*
```release-note
NONE
```

test(e2e): add check for workflow_run success on e2e matrix trigger

---

.github/actions/e2e/cleanup/action.yaml
.github/actions/e2e/create-acr/action.yaml
.github/actions/e2e/create-cluster/action.yaml
.github/actions/e2e/dump-logs/action.yaml
.github/actions/e2e/install-karpenter/action.yaml
.github/workflows/e2e.yaml
test/suites/drift/suite_test.go

Fixes # 
Noticed in some of my testing that the E2E workflows were no longer pointing at the PR test branch, and instead pointing at `main`.
See this PR:
https://github.com/Azure/karpenter/pull/21
with a panic in the drift test suite:
Passing the drift test:
 This PR is changing the workflows to ensure they are checking out the intended branch for testing.
 
None. Needs to be checked into `main`
*
```release-note
NONE
```

test(e2e): fix checkout in e2e test workflow to test the PR's branch

---

.github/actions/e2e/dump-logs/action.yaml
test/suites/drift/suite_test.go

Fixes # 
@tallaxes noticed that the log dump on failure was not working.
Looking into it I noticed that the action was not indented correctly. This PR fixes the indentation, and the issues with the log dump.
I ran the E2E pipeline with a guaranteed failure [in drift] with the log dumps current status in main, which caused it to fail:
https://github.com/Azure/karpenter/actions/runs/6829122309/job/18574667354
Then I ran it with the guaranteed failure [in drift] with the log dump indentation fixed:
https://github.com/Azure/karpenter/actions/runs/6829114912
The fixed indentation executed correctly.
*
```release-note
NONE
```

test(e2e): fix indentation for dump logs

---

.github/actions/e2e/create-acr/action.yaml
.github/actions/e2e/create-cluster/action.yaml
.github/actions/e2e/install-karpenter/action.yaml
.github/workflows/e2e-matrix-trigger.yaml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e.yaml
Makefile-az.mk

Fixes # 
Wanting to give us more flexibility for manual e2e testing, and/or any additional automated testing by opening up the ability to specify the location for a e2e test to be run in.
Here is the branch specific E2E test, which is also targeting `eastus`:
https://github.com/Azure/karpenter/actions/runs/6895118672/job/18758391880
Note: the failures are within GPU is an expected current quota issue, and PVC is flaky atm. With the overall confirmation of the tests running in the given region and the rest of the check-in tests passing, I'm completing this.
*
```release-note
NONE
```

test(e2e): add location option to the e2e pipeline

---

Makefile-az.mk

Fixes # 
On the newest CLI version `--scope` has become a required parameter, and `--resource-group` no longer exists, so updating our make commands to align with this:
- https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#role
*
```release-note
NONE
```

test(make): fixing make + e2e by change to scope for role assignment create

---

test/suites/drift/suite_test.go

Fixes # 
Drift E2E has been a bit flaky with overprovisioning. While investigating I noticed that there was an issue where the drift E2E test was using spot instances:
This should not be the case. We should be using on-demand for drift.
Found there was an issue where we were replacing the Requirements on the nodepool, rather than using the override func. 
Nothing additional.
*
```release-note
NONE
```

test(e2e): fix drift E2E to use ReplaceRequirements

---

go.mod
go.sum
pkg/cloudprovider/cloudprovider.go
pkg/providers/instance/instance.go
pkg/providers/instancetype/suite_test.go

Fixes # 
This PR adds support for TotalRegionalCores errors and makes it more apparent for the customer that this is the root cause of the problem for why their scale up stopped. 
This also modifies the code to use a less generic check for subscription level quota errors, and specifically only marking instances as unavailable if we see a SKUFamily quota error instead of just all subscription level quota errors. 
We also are only logging the Azure Errors and are returning better customer facing errors in this case since they will be viewed in the nodeclaim. 
- Scale Up observing better errors.
```release-note
```

feat: supporting additional handing for TotalRegionalCores quota error, and adding better customer facing error messages on nodeclaim

---

go.mod
go.sum

Fixes # 
Noticed this when running the CI test pipelines:
https://github.com/Azure/karpenter/actions/runs/7201093345/job/19619070945?pr=60
No dep bot PR, so manually bumping
*
```release-note
NONE
```

chore(ginkgo): bump Ginkgo to 2.13.2

---

pkg/utils/gpu.go
pkg/utils/gpu_test.go

Fixes # 
Recently we bumped the grid drivers, to make them compatible with [v12](https://docs.nvidia.com/deploy/cuda-compatibility/#minor-version-compatibility), we also are bumping the cuda driver version as well
See 
- https://docs.nvidia.com/deploy/cuda-compatibility/#minor-version-compatibility
- https://github.com/Azure/AgentBaker/pull/3950
- gpu e2e
```release-note
Bumped Cuda Driver version from 525 to 535
```

chore: bump cuda gpu driver version from 525 to 535

---

pkg/fake/azureresourcegraphapi.go
pkg/fake/communityimageversionsapi.go
pkg/fake/networkinterfaceapi.go
pkg/fake/pricingapi.go
pkg/fake/virtualmachineextensionsapi.go
pkg/fake/virtualmachinesapi.go
pkg/operator/operator.go
pkg/providers/instance/azure_client.go
skaffold.yaml

*These changes are based on feedback from @matthchr*
`var _ instance.NetworkInterfacesAPI = &NetworkInterfacesAPI{}` 
* `make az-all`

chore: Small style + usability refactors for new contributors

---

go.mod
go.sum
pkg/cache/unavailableofferings.go
pkg/cache/unavailableofferings_test.go
pkg/providers/instance/instance.go
pkg/providers/instancetype/instancetypes.go
pkg/providers/instancetype/suite_test.go

Fixes #91 
If spot capacity hits the spot regional cores count, karpenter should fall back onto on-demand. This PR adds that functionality
- make presubmt 
- Manual repro where i first reproed the issue presented in #91 , then proceeded to build a new image with this code and validate it will successfully choose on demand instances if spot capacity is fully used up. 
```release-note
feat: fail-over to on-demand if spot capacity is unavailable
```

fix: mark spot as unavailable on LowPriorityQuota

---

.github/actions/e2e/create-acr/action.yaml
.github/actions/e2e/create-cluster/action.yaml
.github/actions/e2e/install-karpenter/action.yaml
.github/workflows/e2e-matrix-trigger.yaml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e.yaml

Fixes # 
`eastus` should be a better region for our testing, so changing over our defaults.
Did this test with manual input of `eastus`:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/7659927013
Additionally, running the `/test` as normal.
*
```release-note
NONE
```

test(e2e): change to eastus

---

charts/karpenter/templates/deployment.yaml
designs/aks-node-bootstrap.md
designs/gpu-selection-and-bootstrap.md
designs/k8s-node-image-upgrade.md
pkg/fake/types.go
pkg/providers/imagefamily/resolver.go
pkg/providers/instancetype/suite_test.go
pkg/providers/pricing/pricing.go
test/pkg/debug/events.go

Fixes # 
This PR uses https://crates.io/crates/typos-cli in order to fix some typos in docs and go code. The config file I used was:
```toml
[default.extend-words]
als = "als"
ERRO = "ERRO"
```
If you'd like to use it in the future.
There was one extra typo that I found, but I believe it's an imported module, so the typo would need to be fixed there for it to apply:
```diff
diff --git a/pkg/apis/v1alpha2/labels.go b/pkg/apis/v1alpha2/labels.go
index 6b55f4b..2aee2ce 100644
--- a/pkg/apis/v1alpha2/labels.go
+++ b/pkg/apis/v1alpha2/labels.go
@@ -68,7 +68,7 @@ var (
LabelSKUHyperVGeneration,
)
-	AllowUndefinedLabels = func(options scheduling.CompatabilityOptions) scheduling.CompatabilityOptions {
+	AllowUndefinedLabels = func(options scheduling.CompatibilityOptions) …
```

fix typos using https://crates.io/crates/typos-cli

---

.github/workflows/build-publish-mcr.yml
.github/workflows/ci-test.yml
.github/workflows/ci.yml
.github/workflows/deflake.yml
.github/workflows/e2e-matrix-trigger.yaml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e.yaml
.github/workflows/resolve-args.yaml

This tightens the permissions on GitHub Actions, prepping for expected changes to GITHUB_TOKEN. Should resolve all high Token-Permissions security code scanning alerts (https://github.com/Azure/karpenter-provider-azure/security/code-scanning?query=Token-Permissions+is%3Aopen+branch%3Amain+severity%3Ahigh)
* To be tested in CI
```release-note
```

fix(ci): tighten GHA permissions

---

go.mod
go.sum
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/settings/settings.go
pkg/apis/settings/suite_test.go
pkg/cloudprovider/suite_test.go
pkg/controllers/nodeclaim/garbagecollection/suite_test.go
pkg/controllers/nodeclaim/inplaceupdate/controller.go
pkg/controllers/nodeclaim/inplaceupdate/suite_test.go
pkg/controllers/nodeclaim/inplaceupdate/utils.go
pkg/operator/operator.go
pkg/operator/options/options.go
pkg/operator/options/options_validation.go
pkg/operator/options/suite_test.go
pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/resolver.go
pkg/providers/instance/instance.go
pkg/providers/instance/suite_test.go
pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/suite_test.go
pkg/providers/launchtemplate/launchtemplate.go
pkg/test/options.go
pkg/test/settings.go
test/pkg/environment/azure/setup.go

Fixes #  N/A
**Context:**
- Following karpenter-core's effort, we are migrating away from `Settings` to `Options`
- `Settings`, from pkg/api/settings = karpenter-global-settings ConfigMap
- `Options`, from pkg/operator/options = flags OR environment variables
- At the time between "introducing `Options`", which is this PR, and the breaking API change in v0.33(?), which removed ConfigMap support entirely, we will support either options, with `Options` taking precedence
**Expected impact from this change:**
- `Options`: flags and environment variables is now supported as an alternative for all values currently utilizing the ConfigMap
- ConfigMap can be safely removed once we create the container using flags or environment variables
**Non-impact:**
- ConfigMap is still …

chore: karpenter-global-settings migration

---

Makefile-az.mk

Follow-up to #131. Currently the e2e test suite + local dev via `make az-all` is blocked by this. The if condition was always evaluating as true, because non-empty strings in bash are truthy.
* `make az-mkrg`, e2e suite (passed, except for utilization, not due to this issue)

chore: az-mkrg fix

---

.devcontainer/devcontainer.json

Removes the remaining customization of kubebuilder assets location in devcontainer / Codespace, leftover from https://github.com/Azure/karpenter-provider-azure/pull/118. This should fix panic on `make presumbit` on brand new Codespace.
`make presubmit` on new codespace
```release-note
```

chore: remove custom kubebuilder assets location

---

.github/workflows/build-publish-mcr.yml

Fixes the name of the repository to publish to, for correct propagation to MCR
*
```release-note
```

Update build-publish-mcr.yml to reference correct repo

---

pkg/apis/v1alpha2/labels.go
pkg/operator/operator.go
pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/suite_test.go
pkg/test/environment.go

fix: adding topology label to normalized labels
Fixes # 
workload using topology.disk-csi-azure.com/zone in node affinity would fail to schedule. Karpenter has a concept for translating these labels in its scheduling code to normalize the values. This PR Changes topology.disk.csi.azure.com to map to the standard topology label. 
This PR also adds additional testing around well known labels and pod node selector requests. This discovered the unimplemented Isolated size and Confidential well known labels we expose. Removing them until we have more concrete usecases for them. They are not in the docs so no docs update required. 
Scale up, workload with `topology.disk.csi.azure.com/zone1 schedules fine.  …

fix: add topology.disk.csi.azure.com/zone to normalized labels

---

.github/workflows/build-publish-mcr.yml

Fixes # 
We have a set of overall work to switch the build and release pipeline to 1ES. This step converts the workflow within the repo.
Ensured that the updated workflow will succeed by running it with the build, but not publishing:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/8333362669/job/22806353399
*
```release-note
NONE
```

chore(release): onboard to 1ES

---

cmd/controller/main_ccp.go

Fixes # 
Recent core version bump has an interface change. The change was addressed in the default mode, but not ccp mode, which currently need to be tested (by building the image) manually.
This PR address that change.
* Manually
```release-note
```

fix: core v0.34 bump neglected NewControllers interface change in ccp mode

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go

Fixes #197  
We currently hardcode managed identity enablement for AKS node bootstrapping script to be `false`, which is incorrect as we need it to be `true` per our managed identity support. This PR is a quick fix for this. See the linked issue for a consequence of this bug.
* Manually in NAP environment by assigning `acrpull` role to the kubelet identity and compare the results before and after the fix. This role assignment should be equivalent to `attach-acr`.
```release-note
- Fix an issue where provisioned node(s) do not have permission to pull images from Azure Container Registry (ACR) for pods even after integrating with the cluster
```

fix: managed identity not being enabled for nodes

---

Makefile-az.mk

* changed to False from false. 
* can make a unique AZURE_ACR_NAME
Fixes # 
'az group exists' printed true/false as capital letter.
So i added the ignore-case option(-i).
Also AZURE_ACR_NAME should be unique. but if the codespace is not using, only set karpenter as the AZURE_ACR_NAME 
make az-all
*
NONE
```release-note
```

test: output of grep command is capital letter and AZURE_ACR_NAME should be unique 

---

Makefile-az.mk

Fixes # 
I've found I've been wanting this make command myself, so adding one to the file.
*
```release-note
NONE
```

test(make): add taint node make command

---

Makefile-az.mk

Fixes # 
@tallaxes noticed a few solid changes to make to the command after completion, so addressing them here:
- https://github.com/Azure/karpenter-provider-azure/pull/234
Ran this on a newly created cluster and it tainted the nodes
*
```release-note
NONE
```

test(make): minor follow up on taint make command

---

test/pkg/environment/common/expectations.go

Fixes # NA 
Removing some old helpers remaining from aws port of e2es
/test
```release-note
```

chore: removing eni helpers

---

hack/release/common.sh

Fixes # 
This PR adds the required changes to support running these release scripts for macos. The only conflict is the date module as macos date is different from the gnu date format. 
*
```release-note
```

fix: amending release scripts to work for macos

---

hack/release/common.sh

Fixes # 
Found there is a missing slash in the cosign logic for helm which is an issue for releasing. Fixing.
Nothing additional.
*
```release-note
NONE
```

chore(release): fix missing slash in helm cosign

---

Makefile
Makefile-az.mk
README.md
hack/deploy/create-cluster.sh

Fixes # 
When testing `v0.4.0.rc.3` I noticed the service account federated credential not aligning correctly. The namespace within `create-cluster.sh` should be `karpenter`, so fixing.
tested this exact change with `v0.4.0.rc.3` on a different branch/code space and worked correctly.
*
```release-note
NONE
```

chore(make): fix create-cluster.sh deployment script to work with correct namespace

---

hack/release/common.sh

Fixes #294
A bug was found with snapshot commands in the recent update for the release scripts:
- https://github.com/Azure/karpenter-provider-azure/commit/5729c52f61c74c4fb73d825e808e7c5458e5634d
Tested `make snapshot` and `make az-all-user` in a codespace
*
```release-note
NONE
```

fix(snapshot): fix snapshot unset bash var bug

---

pkg/cloudprovider/cloudprovider.go

Using lo.FromPtr() since its a bit safer
```release-note
```

chore: nit using lo.FromPtr is safer than directly accessing the pointer

---

.devcontainer/devcontainer.json

When using the github CLI to access codespaces, you cannot ssh without this plugin. 
gh codespace ssh -c reimagined-fortnight-<redacted>    
Starting codespace ⢿
Starting codespace ⣾
Linux codespaces-ccffc6 6.2.0-1019-azure #19~22.04.1-Ubuntu SMP Wed Jan 10 22:57:03 UTC 2024 x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
@Bryce-Soghigian ➜ /workspaces/aks-karpenter (bsoghigian/codespaces) $
```release-note
```

feat: extending devcontainers to work with github cli ssh access

---

pkg/providers/instancetype/instancetype.go

The nodeClass.Spec.OSDiskSizeGB dereference actually crashes when being called from the cloudprovider GetInstanceTypes if the nodepool is nil.
Fixes #315 
*
```release-note
```

chore: using lo.FromPtr is safer than directly accessing the pointer

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go

Fixes # 
*
```release-note
```

refactor: cgroupsv2 bool can be defaulted

---

hack/validation/common.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml

Fixes #339 
See the issue.
This change should not undo the continuous drift issue that https://github.com/Azure/karpenter-provider-azure/pull/274 fixes, as adding zones requirements is still prohibited on the nodepool CRD, which is the (intentionally) user-facing interface.
Current drift logic also "ignore" requirements that exist in NodeClaims, but not NodePools.
* Manual inspection from reproduction
* NAP E2Es
* Check-ins here
```release-note
- Fix the issue where Karpenter/NAP sometimes cannot create nodes/nodeclaims for workloads with zone affinity constraints
```

fix: reallowing nodeclaim zones to fix node/nodeclaim creations for workloads with zone affinity constraints

---

test/suites/drift/suite_test.go

Fixes # 
Upgrading older node image versions to new ones to make sure e2e doesnt break during deprecation
```release-note
```

fix: upgrading node image versions in drift e2e since we are deprecating older node image versions

---

pkg/utils/gpu.go
pkg/utils/gpu_test.go

See: https://github.com/Azure/AgentBaker/pull/4429 for additional context as to why we are bumping. 
```release-note
```

chore: bumping the grid driver affecting linux kernels 5.15.1063+ versions

---

.github/workflows/ci-test.yml
go.mod
hack/toolchain.sh
pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl
pkg/providers/instancetype/suite_test.go
pkg/utils/utils.go

Fixes # NA
Bootstrap for 1.30 will fail if we have the --azure-container-registry-config flag specified. 
```
azureuser@aks-general-purpose-78r6l:~$ journalctl -u kubelet.service
---
May 10 08:31:26 aks-general-purpose-78r6l kubelet[10604]: E0510 08:29:13.285779   10604 run.go:74]"command failed" err="failed to parse kubelet flag: unknown flag: --azure-container-registry-config"
May 10 08:31:26 aks-general-purpose-78r6l kubelet[13211]: E0510 08:31:26.037146   13211 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --azure-container-registry-config"
May 10 08:31:26 aks-general-purpose-78r6l systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
May 10 08:31:26 aks-general-purpose-78r6l systemd[1]: kubelet.service: Failed …
```

feat: supporting 1.30 bootstrap via enabling out of tree credential provider

---

.github/workflows/build-publish-mcr.yml

Fixes # 
Working towards a more automated release process. Removing the manual step of triggering with specified tag to automatic trigger based off tagging.
This is aligned behavior with the aws provider:
- https://github.com/aws/karpenter-provider-aws/blob/9e113aaca23bce17e99cd6f14447927e7c89e3d4/.github/workflows/release.yaml
*
```release-note
NONE
```

chore(release): switch release workflow to have tag trigger

---

.github/workflows/release-trigger.yaml
.releaserc.yaml

Fixes # 
We currently have to create the github release, and its release notes manually.
The repo `aws` is using is no longer maintained:
- https://github.com/aws/karpenter-provider-aws/blob/2e907f90b82ea04ff76da13c5a486c71a421e827/.github/workflows/release.yaml
Because of this there are two approaches I'm looking at for our more automated release process.
I looked over the recommended substitutes and found that I think the [action-gh-release](https://github.com/softprops/action-gh-release) might match our current desires the best. Its closest to the old action. However, the [semantic-release](https://github.com/semantic-release/semantic-release) action could also be useful with some of its additional feature sets, so want to explore that option as well, even though more …

chore(release): add new semantic-release workflow

---

.releaserc.yaml

Fixes # 
accidentally used `@semantic-release/git` at first. Fixing to `@semantic-release/github`
Ran the workflow and verified it configured plugins correctly:
https://github.com/Azure/karpenter-provider-azure/actions/runs/9718846813/job/26827532131
*
```release-note
NONE
```

chore(release): correct plugin to @semantic-release/github

---

.github/workflows/e2e-matrix-trigger.yaml

Fixes # 
We've been experiencing some allocation issues within the current testing regions. 
Did some testing to find a new region, which `westus3` seems to be rather well suited for our needs, so switching the testing pipeline there.
Ran the E2E pipeline for `westus3`:
https://github.com/Azure/karpenter-provider-azure/actions/runs/9964029669/job/27531436071
While not all successful, did a sanity check within the subscription on quota, and public doc support for multi-zone region, and this appears to be a good region change:
https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support
*
```release-note
NONE
```

test(e2e): switch to westus3 for e2e

---

.github/workflows/ci-test.yml
hack/toolchain.sh
pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/instancetype/suite_test.go

Fixes # 
For supporting 1.31 node bootstrapping, we need to remove the `--keep-terminated-pod-volumes` from the kubelet flags. This pr introduces that logic into our bootstrapping contract. 
- make presubmit 
- manual testing with kubelet version set to 1.31
```release-note
Support 1.31 node bootstrapping via removing the --keep-terminated-pod-volumes flag that was removed in kubelet version 1.31. 
```

fix: removing --keep-terminated-pod-volumes from kubelet flags and adding k8s 1.31 to ci-test

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go

Fixes #411
https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/imagefamily/bootstrap/aksbootstrap.go#L425
```
// CredentialProviderURL returns the URL for OOT credential provider,
// or an empty string if OOT provider is not to be used
func CredentialProviderURL(kubernetesVersion, arch string) string {
  minorVersion := semver.MustParse(kubernetesVersion).Minor
  if minorVersion < 30 { 
    return ""
  }
```
Looks like from this code for out of tree provider we default to not including the settings for out of tree provider if CredentialProviderURL is empty. 
DisableKubeletCloudCredentialProviders | false | Alpha | 1.23 | 1.28
-- | -- | -- | -- | --
DisableKubeletCloudCredentialProviders | true | Beta | 1.29 | –
We don't have the logic conditionally …

fix: set `DisableKubeletCloudCredentialProviders=false` for versions without OOT credential provider (1.29)

---

.github/actions/e2e/create-acr/action.yaml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e.yaml
Makefile
Makefile-az.mk
pkg/apis/crds/karpenter.sh_nodepools.yaml
test/suites/acr/suite_test.go

Fixes # 
As part of the efforts to fix 1.30 bootstrap we removed a flag that removes functionality for out of tree providers. One of the side affects of this is that ACR Pull will not work in the same way. We needed a way to validate this image pull works in a reproducible and consistent way. 
This test suite is that. Currently it has to be ran locally to target specific k8s versions so a nice followup at lower priority would be to add the ability to run our e2es against a specific k8s version. 
- make az-e2etests
```
[251.679 seconds]
------------------------------
Ran 1 of 1 Specs in 251.874 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestAcr (251.87s)
PASS
ok …
```

test(e2e): validate that pulling from an acr registry attached to aks via --attach-acr with karpenter nodes works

---

.github/workflows/approval-comment.yaml
.github/workflows/ci-test.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deflake.yml
.github/workflows/dependency-review.yml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e.yaml
.github/workflows/release-trigger.yaml
.github/workflows/resolve-args.yaml
.github/workflows/scorecards.yml

Switch to Harden Runner `egress-policy: block`, add selected `allowed-endpoints`. Also `disable-telemetry: true` for now.
The endpoints come from StepSecurity insights for corresponding runs (such as [this one](https://app.stepsecurity.io/github/Azure/karpenter-provider-azure/actions/runs/10379526294?jobid=28737859970&tab=recommendations); "Recommendations" tab as base, "Networks Events" for further drill down), with some selected wildcarding (to accommodate variations) and removals (mostly things that are no longer used, but might still be reported in the cumulative insights). Notes and outliers:
* The largest set of endpoints is (naturally) used by E2E tests, which use az CLI, create AKS clusters, and run tests. The only one using wildcards.
* Historically observed but …

fix: harden harden-runner egress policy

---

pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl

Fixes bootstrap failure on latest VHD images by specifying default values for required IMDS restriction settings
* manual local testing
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/10890699757
```release-note
```

fix(bootstrap): add defaults for required IMDS restriction settings

---

examples/v1beta1/general-purpose.yaml
examples/v1beta1/multi-arch.yaml
examples/v1beta1/system-surge.yaml
test/pkg/environment/azure/environment.go

Fixes # 
See the following thread for why we need the given startupTaint:
- https://karpenter.sh/docs/faq/#why-do-i-see-extra-nodes-get-launched-to-schedule-pending-pods-that-remain-empty-and-are-later-removed
As our testing, and main example cases all use Cilium, adding this to all the areas.
Tested [general-purpose.yaml](https://github.com/Azure/karpenter-provider-azure/pull/508/files#diff-d76365775af789aed6414b86f28136204ea77b35ee25349d76eb590b9d7c03b9) in self-hosted codespace setup.
Also, ran E2E suite:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/11149258534
- https://github.com/Azure/karpenter-provider-azure/actions/runs/11150952645
```release-note
NONE
```

test(Cilium): add CiliumAgentNotReadyTaint to prevent overprovisioning

---

examples/v1beta1/general-purpose.yaml
examples/v1beta1/multi-arch.yaml
examples/v1beta1/system-surge.yaml
test/pkg/environment/azure/environment.go

Adds cilium startup taint (https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint) and add cillium ebpf-dataplaine label (so that Karpenter can take the corresponding DaemonSet into account when computing the expected overhead), to example and default E2E NodePools.
* E2E - https://github.com/Azure/karpenter-provider-azure/actions/runs/11261786845
```release-note
```

fix(provisioning): add cilium taint and label

---

pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
pkg/providers/imagefamily/resolver.go

Fixes # 
KubeletConfig retrieved from nodeClaim doesn't seem to have a proper defaulting(?), which could returns invalid values (e.g., out of range) when populating ProvisionProfile. The logic added here should isolate non-pointer values (which cannot be "unpopulated" by being nil) and have an empty check.
Also, new unregistered startup taints defaulting method went under the radar during the merge, making it ineffective for CustomScripts bootstrapping. This should fix it, and have similar spots scanned.
* Manual provisioning test
* Inspecting ProvisionProfile values
```release-note
NONE
```

fix: follow-up fixes on bootstrappingclient mode after integration testing with v1

---

docs/workshops/10_multi_node_consolidation.md
docs/workshops/12_scheduling_constraints.md
docs/workshops/13_disruption_controls.md
docs/workshops/1_aks_cluster_creation_and_install_karpenter.md
docs/workshops/9_single_node_consolidation.md
docs/workshops/kubecon_azure_track.md
docs/workshops/reestablish_env.md

Fixes # 
Adding documentation for handling the optional steps within the KubeCon workshop.
Minor adjustments within the docs as well.
Tested all of the new optional steps + cleanup in the Cloud Shell environment.
*
```release-note
NONE
```

docs(workshop): add documentation for kubecon optional steps

---

Makefile-az.mk

Fixes # 
I've been working though some tests of karpenter, and have noticed having the logs in a more readable form is nice. Adding a pretty print command for the klogs.
Ran the command on a cluster with karpenter installed
*
```release-note
NONE
```

test(make): add pretty print command for klogs

---

Makefile-az.mk
examples/v1/general-purpose.yaml
examples/v1beta1/general-purpose.yaml

Fixes # 
I noticed that the `az-run-sample` make command was still using, 1vbeta, and updating it here, along with updating the `v1` file in accordance with recent optional settings.
`make az-run-sample`
*
```release-note
NONE
```

test(make): update `az-run-sample` to v1

---

.github/actions/install-deps/action.yaml
.github/dependabot.yaml

Fixes # 
This PR updates the `install-deps` action and dependabot config to ensure that the correct versions are used and the action runs as expected. (The rename of the file to '.yaml` extension makes it so it is properly picked up by hack/github/depdendabot.sh)
* `hack/github/depednabot.sh`
```release-note
```

chore: fix install-deps action and dependabot config

---

Makefile

Fixes # 
* Speed up ci-test (don't always run race checks)
* Make presubmit the same as ci-test for consistency
* Add license checks
```release-note
```

chore: update Makefile test targets

---

karpenter-values-template.yaml

From v1.0.x, sig.k8s.io/karpenter uses `DISABLE_LEADER_ELECTION` env variable
* local debugging
```release-note
```

fix: disabling leader election

---

test/suites/drift/suite_test.go

Removes unnecessary drift feature override (no longer a feature, always enabled) in E2E. This also removes eliminates restart of Karpenter due to env var changes.
* `make az-e2etest`
```release-note
```

fix(e2e): remove drift feature gate override

---

pkg/providers/instance/armutils.go
pkg/providers/instance/instance.go

Cherry-picks #633 into release-v0.6.x branch
```release-note
```

[release-v0.6.x] fix: Resolve errors for resource not found (#633)

---

go.mod

The CI is failing due to vulncheck. We get the following two cves 
[242](https://github.com/Azure/karpenter-provider-azure/actions/runs/13001878487/job/36261959788?pr=642#step:6:243)Vulnerability #1: GO-2025-3420
[243](https://github.com/Azure/karpenter-provider-azure/actions/runs/13001878487/job/36261959788?pr=642#step:6:244)    Sensitive headers incorrectly sent after cross-domain redirect in net/http
[244](https://github.com/Azure/karpenter-provider-azure/actions/runs/13001878487/job/36261959788?pr=642#step:6:245)  More info: https://pkg.go.dev/vuln/GO-2025-3420
[245](https://github.com/Azure/karpenter-provider-azure/actions/runs/13001878487/job/36261959788?pr=642#step:6:246)  Standard library
[246](https://github.com/Azure/karpenter-provider-azure/actions/runs/130018784 …

fix: https://pkg.go.dev/vuln/GO-2025-3420 by upgrading from go 1.23.0 -> 1.23.5

---

Makefile-az.mk
hack/deploy/configure-values.sh

In the vnet guid resolution pr stage 1, we do not properly set vnet guid for managed vnet, this pr refactors the configure-values for vnetsubnetid and vnetguid to be less confusing and fixes that bug
See failure from before here: https://github.com/Azure/karpenter-provider-azure/actions/runs/13146914697/job/36686962775 
See how it now passes: https://github.com/Azure/karpenter-provider-azure/actions/runs/13168522212/job/36754158929
Ran e2e tests to ensure we set the value in the charts correctly for managed. 
```release-note
```

refactor: cleaning up the vnet guid resolution and the vnet subnet id in configure-values.sh

---

pkg/controllers/nodeclaim/garbagecollection/suite_test.go
pkg/providers/instance/suite_test.go
pkg/test/expectations/expectations.go

One of the cleanup items from the network interface garbage collection pr was to remove this minor helper I added. This pr does that.
- make test
```release-note
```

test: removing NoError in favor of consistent Expect(err).ToNot(HaveOccurred()) throughout the codebase

---

charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml

Seems make presubmit somehow was bypassed, this updates that. If you run make presubmit on main, it generates content. 
*
```release-note
```

fix: make presubmit

---

pkg/utils/opts/armopts.go

This change utilizes Service Hub [logging policy](https://github.com/Azure/aks-middleware/blob/main/http/client/azuresdk/policy/policy.go) to instrument the pipeline used to send requests to ARM in order to log out responses for logging/monitoring purposes.
Example logs generated during E2E testing
E2E tests
*
```release-note
```

Utilizing SH Logging Policy for ARM Track 2 SDK Calls

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/instancetype/suite_test.go
pkg/providers/launchtemplate/launchtemplate.go

* fix: setting network plugin to none in the agentbaker contract if we are using overlay net plugin mode. This will delegate the installation of the cni to daemonsets (azure-cns) etc. This also introduces a label azure-cni-overlay which adds better consistency between karpenter provided nodes and nodes provided from aks. We also introduce tests to explicitly validate that if the network plugin mode on the cluster is azure and uses azure cni overlay, that we properly delegate that installation
* fix: ci
* refactor: renaming cni label var
* modifying comment
* style: renaming vars to not have vnet prefix
* test: adding tests for the different cni modes on labels
* refactor: renaming test
* feat: supporting cilium + nodesubnet case

feat: add azure-cni-overlay label and set network plugin to none in some cases

---

pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl

Fixes #723
This adds the `MCR_REPOSITORY_BASE` setting to bootstrap, which is apparently required by `v202503.02.0` VHD image
* manual scaleup
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/13709312852 (pending)
* independent testing of snapshot image
```release-note
Adds `MCR_REPOSITORY_BASE` setting to bootstrap script to fix bootstrap of `v202503.02.0` VHD image
```

fix: add required `MCR_REPOSITORY_BASE` to bootstrap

---

pkg/operator/operator.go
pkg/providers/imagefamily/resolver.go
pkg/providers/launchtemplate/launchtemplate.go
pkg/test/environment.go

Fixes # 
Currently working on a refactor of the `imagefamily` package to leverage the new status information on node images and kubernetes version for provisioning. Felt this refactor could be broken out into a clean, simple, and smaller PR.
Nothing additional (just normal check-in tests, and running E2E manually)
- E2E test: https://github.com/Azure/karpenter-provider-azure/actions/runs/13999763078
```release-note
NONE
```

chore(refactor): add Resolver interface in refactor of imagefamily package

---

charts/karpenter/templates/clusterrole-core.yaml

Fixes # 
As part of our plan to upgrade to v1.1.x which remove webhooks, the `.status.storedVersions` have to be handled correctly for existing v1beta1 instances in advance, which these updated roles will allow self-hosted to do.
- E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/14135341920
```release-note
Updating roles for self-hosted to allow correct transition of `.status.storedVersions` as required for existing v1beta1 instances, required for future upcoming update to upstream v1.1.x core dependency change.
```

chore(roles): update roles for self-hosted to support v1 webhook migrations

---

Makefile-az.mk

* Add `az-cleanenv` target to clean up resources before running e2e tests.
* Set environment variables before running e2e tests (required since https://github.com/Azure/karpenter-provider-azure/pull/686)
* `make az-e2etests`
```release-note
```

fix(e2e): clean up resources and set environment variables before e2e

---

.pre-commit-config.yaml
charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
test/suites/integration/termination_test.go

Fix termination tests under Integration suite by marking the prematurely added "drain pods on a node in order" test as pending, until update of `sigs.k8s.io/karpenter` to 1.1.x which ensures the order (and fixes a bug in `test.DaemonSet` that does not propagate labels from `options.PodOptions`)
* `make az-e2etest` with focused test
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/14238150138 (https://github.com/Azure/karpenter-provider-azure/pull/766/commits/35af93566d28bf5c1d1324d5fa6f1e3443661fa7)
```release-note
```

test(integration): mark "drain pods in order" as pending

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/bootstrap/staticvalues.go

Fixes # 
I discovered there was a bug within the provisioning where bootstrapping configuration can be leaked between different instances of provisioning. This is particularly the case with `kubeletFlagsBase`, which is stored as a `var`, causing it to keep info between provisioning requests. This surfaced as an issue when implementing a self-hosted test for upgrading to kubernetes version 1.31.6, as a kubelet flag that should have been removed for that version was still around due to nodes being on 1.30.x having stored the flag.
- Tested deepcopying of `kubeletFlagsBase` locally fixes the k8s e2e test.
- Also, can be seen to fix KubernetesUpgrade test suite: 
https://github.com/Azure/karpenter-provider-azure/actions/runs/14 …

fix(bootstrapping): Refactor bootstrapping to encapsulate between provisioning

---

.devcontainer/devcontainer.json
.github/workflows/e2e.yaml

Pin skaffold version in devcontainer to 2.14.2 (latest = 2.15.0 appears to have broken helm overrides) and make e2e match dev
* `make az-run`
```release-note
```

fix: pin skaffold version (and have e2e match dev)

---

Makefile

Fix periodic [periodic deflake run](https://github.com/Azure/karpenter-provider-azure/actions/workflows/deflake.yml) using `make deflake`, which should not run indefinitely, by moving `--until-it-fails` to the new `deflake-until-it-fails` target instead.
* `make deflake`
```release-note
```

fix(ci): remove `--until-it-fails` from `make deflake`

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go

Update credential provider versions (and add 1.32); follow-up to #808 
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/14545424719 ✅
```release-note
```

chore: update versions of credential provider (and add 1.32)

---

pkg/apis/v1alpha2/suite_test.go
pkg/controllers/nodeclaim/inplaceupdate/suite_test.go
pkg/test/environment.go

Make test environment respect options from context, for better testability
```release-note
```

fix: take test options from context

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/events/events.go
pkg/providers/instance/instance.go
pkg/providers/instance/suite_test.go
pkg/providers/instancetype/suite_test.go

* NIC creation is still blocking, but that may change in the future if we roll NIC creation into VM creation.
* instance provider now returns a VMFuture, which CloudProvider polls in a separate goroutine. If an error is encountered, the NodeClaim is deleted and the pending pods will trigger another NodeClaim to be created.
This improves disruption speed significantly, but there is still slowness in disruption (caused by core as far as I can tell).
Fixes #600
* Unit tests
* E2E tests (pass 1): https://github.com/Azure/karpenter-provider-azure/actions/runs/14605092382 - this had some flakes but I re-ran them locally and they passed.
* E2E tests (pass 2): https://github.com/Azure/karpenter-provider-azure/actions/runs/14673602666 - running a second pass because …

feat: switch CloudProvider Create to be (mostly) non-blocking

---

pkg/cloudprovider/cloudprovider.go

See: https://learn.microsoft.com/en-us/azure/aks/node-auto-repair#how-aks-checks-for-notready-nodes for that repair SLO.
It wasn't
```release-note
```

feat: duration for node auto repair should match aks customer promise

---

test/pkg/environment/common/environment.go
test/pkg/environment/common/expectations.go

When running our test suite against other cni configurations, it will fail. This change makes the configurations dynamic
- make az-all-cniv1 
- make az-e2etest
```release-note
```

test: making startup taints and annotations for cilium conditional on the cilium ds being present

---

test/suites/drift/suite_test.go

Fix drift E2E suite failures and deflake. 
* Have VM SKU selection use CPU count instead of specific SKU (DSv2 series may no longer be available in some regions).
* Deflake non-empty replace drift test
* Remove outdated comments
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/14819482094 ✅
```release-note
```

test(e2e): fix drift suite

---

test/suites/gpu/suite_test.go

Validating that node auto repair is not deleting gpu nodes before they join the cluster and run workloads.
E2E Tests: https://github.com/Azure/karpenter-provider-azure/actions/runs/14809391794/job/41582237267
```release-note
```

test: node auto repair doesn't remove our gpus

---

cmd/controller/main.go
cmd/controller/main_ccp.go
go.mod
pkg/operator/operator.go

Add wait for CRDs on start, prior to starting core operator with timeout (2m) - though note that liveness probe, if not tuned, is likely to kill the process earlier.
We had removed the alternative operator that waited for CRDs. The current core operator implementation ["fails open"](https://github.com/kubernetes-sigs/karpenter/pull/1683) on missing CRDs, proceeding without configuring indexers. Unfortunately, for now there are controller (including in core) that use caching client with `client.MatchingFields` option, which require indexes. These controllers will stay broken after CRDs are deployed, since there is nothing that would (re-)create the indexes then. On top of this, after CRDs are in place, it will stop exiting on CacheSyncTimeout (2m by default), so it will …

feat: wait for CRDs

---

charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
hack/validation/labels.sh
hack/validation/requirements.sh
pkg/apis/crds/karpenter.sh_nodeclaims.yaml
pkg/apis/crds/karpenter.sh_nodepools.yaml
pkg/apis/v1alpha2/labels.go
pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/suite_test.go
test/suites/scheduling/suite_test.go

Remove support for `sku-encryptionathost-capable` label/selector, until we actually support encryption at host
* `make presubmit` 
```release-note
```

BREAKING CHANGE: remove support for `sku-encryptionathost-capable` label/selector

---

pkg/utils/opts/armopts.go

Use defaults for SDK retry options, reducing retries to 3 from 20, and initial delay to 4s from 5s
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/14849391618 (pending)
```release-note
```

fix: use defaults for SDK retry options

---

pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go

Make artifact streaming conditional on architecture (x64 only) and distribution (only the currently supported ones)
* `make presubmit` (though w/o unit tests for bootstrapping client)
* E2E: self-hosted does not exercise bootstrap client, will be tested elsewhere
```release-note
```

fix: make artifact streaming conditional on architecture and distribution

---

pkg/cloudprovider/suite_test.go
pkg/controllers/nodeclaim/inplaceupdate/suite_test.go
pkg/fake/azureresourcegraphapi_test.go
pkg/fake/virtualmachinesapi.go
pkg/providers/instancetype/suite_test.go
pkg/utils/utils.go

Fixes # 
I noticed the `MkVMID` method was sitting in a prod pkg which concerns be quite a bit. Thankfully it wasn't reference anywhere expect tests. Moving it to the `fake` pkg where it belongs.
- E2E Runs:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15056131604 (latest)
```release-note
NONE
```

test(fake): move MkVMID to fake pkg

---

go.mod
go.sum
pkg/providers/instance/instance.go
pkg/providers/instancetype/suite_test.go

Fixes #762 
Handle OverconstrainedZonalAllocation, OverconstrainedAllocation and AllocationFailure errors when creating new instances, marking VM sizes/Zones/Capacity types as unavailable depending on the error  type.
- Unit testing
- E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/15075909021 (pending)
```release-note
Offerings will be marked as unavailable when AllocationFailure, OverconstrainedAllocation or OverconstrainedZonalAllocation error is returned from Azure.
```

feat: handle OverconstrainedZonalAllocation, OverconstrainedAllocation and AllocationFailure errors when creating new instances

---

pkg/cloudprovider/drift.go
pkg/cloudprovider/suite_test.go
pkg/test/utils.go

Fixes # 
Currently we error out on the case of NotFound and Deleting nodes. However, these cases are actually expected to be able to occur during the lifecycle of nodeclaims, so switching their handling to return no error.
- E2E runs:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15056128931
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15056727146
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15057293409
- Got a failure in NodeClaim, and Drift tests.
- NodeClaim appears to be a flake, and failure doesn't seem related to this change. It failed waiting for the initialized node count to be 1 
- Drift case appears to be unrelated. I dug into the Drift code, and don't …

fix(drift): improve NotFound and Deleting Nodes case in Drift

---

pkg/apis/v1beta1/labels.go
pkg/cloudprovider/drift.go
pkg/cloudprovider/suite_test.go
pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
pkg/providers/imagefamily/labels/labels.go

* Add kubernetes.azure.com/kubelet-identity-client-id label to all nodes, to match what AKS does.
* Drift nodes if the expected kubelet-identity-client-id has changed.
* Does not drift if the node doesn't have the AKS Kubelet ClientID label set.
* Unit tests
* Manual test with NPS bootstrap, shows nodes now come up with this label: `kubernetes.azure.com/kubelet-identity-client-id=fcd9a498-b00b-4757-8c2a-90f6ede47610`. Changing it at the configmap scope results in drift and the new node coming up with the new label.
```release-note
Added the kubernetes.azure.com/kubelet-identity-client-id to all nodes and drifts nodes if the expected kubelet-identity-client-id has changed.
```

feat: drift for Kubelet Client ID

---

cmd/controller/main.go
pkg/controllers/nodeclass/status/kubernetesversion_test.go
pkg/controllers/nodeclass/status/suite_test.go
pkg/operator/operator.go
pkg/providers/imagefamily/image.go
pkg/providers/imagefamily/kubernetesversion.go
pkg/providers/instancetype/suite_test.go
pkg/test/environment.go

Fixes # 
This is a follow up to previous refactoring of the `imagefamily` providers logic for provisioning. 
First refactor covered in this PR, splitting apart the provider, to have the KubernetesVersionProvider separate.
- E2E
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15149246588
- Failure in [should delete pod with do-not-disrupt when it reaches its terminationGracePeriodSeconds](https://github.com/Azure/karpenter-provider-azure/actions/runs/15149246588/job/42592111041#step:18:4477)
- appears there is a race condition for the amount of time between the node deleting, and the watch for `ConsistentlyExpectHealthyPods`. Seeing the logs between being over `100*time.Millisecond`, which is the buffer …

chore(providers): factor out KubernetesVersion provider

---

pkg/cache/unavailableofferings.go

`MarkSpotUnavailableWithTTL` now correctly passes value of `ttl` param to the function it calls. This PR is a no-op - the only call site of `MarkSpotUnavailableWithTTL` passes in a 1hr long ttl, which is the same as currently used hard-coded value in `MarkSpotUnavailableWithTTL`.
* 
```release-note
NONE
```

fix: use ttl param in MarkSpotUnavailableWithTTL

---

pkg/providers/imagefamily/nodeimage_test.go
pkg/providers/imagefamily/suite_test.go

Note to other change authors: Do not call coretest.NewEnvironment without calling env.Stop().
Also, it's strongly recommended to not launch multiple envs per suite, because each env is a kube-apiserver + etcd pair that has a moderate amount of cpu/memory overhead.
```release-note
NONE
```

chore: Fix envtest leak when running tests

---

pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/suite_test.go

Boolean-valued requirements (like `sku-storage-premium-capable`) should allow both "true" and "false" value in selectors. (Only "true" was supported.)
```release-note
```

fix: capture both values for boolean requirements

---

pkg/providers/instance/instance.go
pkg/providers/instance/instance_test.go

Adjusts TTL for unavailable offerings when allocation related failures are reported back by Azure, adds unit tests
```release-note
Adjusts TTL for unavailable offerings when Azure reports Allocation related errors from 3 minutes to 15 minutes.
```

fix: adjust TTL for unavailable offerings when allocation error happens

---

pkg/fake/networksecuritygroupapi.go
pkg/operator/operator.go
pkg/providers/instance/azure_client.go
pkg/providers/instance/instance.go
pkg/providers/instance/instance_test.go
pkg/providers/networksecuritygroup/networksecuritygroup.go
pkg/providers/networksecuritygroup/suite_test.go
pkg/test/environment.go
pkg/test/networksecuritygroup.go

This provider discovers the AKS Managed NSG and caches its details for the life of the process.
This is a prerequisite for fixing #562.
Note that since this provider is not actually called in the real production code at the moment, it doesn't do anything yet.
* Unit tests
```release-note
NONE
```

chore: add new NSG provider

---

pkg/operator/options/options.go
pkg/providers/instance/instance.go
pkg/providers/instance/suite_test.go
pkg/providers/instancetype/suite_test.go
pkg/test/environment.go
pkg/test/options.go
pkg/utils/utils.go
pkg/utils/utils_test.go
test/pkg/environment/azure/environment.go
test/pkg/environment/azure/expectations.go
test/suites/integration/subnet_test.go

This mirrors what AKS does. This is not required in managed VNET mode because then the NSG is attached to the Subnet (created by AKS), so it doesn't need to be attached to each NIC individually.
Fixes #562.
This supersedes #610, which should be closed.
* Unit tests
* E2E tests (see newly added test). Full E2E run results: https://github.com/Azure/karpenter-provider-azure/actions/runs/15312805268
* Manually tested the scenario reported in #562 using `make az-all-custom-vnet`
```release-note
Fix bug which caused load balancing to not work correctly in BYO VNET scenarios.
```

fix: Attach Managed NSG to NIC when in BYO VNET mode

---

Makefile-az.mk

Removed the (I believe unneeded) NetworkContributor at cluster scope in in the non-byo-vnet case.
This was found due to us double-assigning the same role assignment in the BYO case, which doesn't work on unmanaged devices due to a bug in az cli, see https://github.com/Azure/azure-cli/issues/31579
* E2E
```release-note
NONE
```

fix: Fix double role assignment in custom-vnet case

---

.github/workflows/ci-test.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/deflake.yml
.github/workflows/e2e.yaml

Add `release-assets.githubusercontent.com` to Harden Runner allowed-endpoints, to fix selected CI tests. The issue is not observed on all builds, but some failures are clearly due to this ([example](https://github.com/Azure/karpenter-provider-azure/actions/runs/15548557535/job/43782630888?pr=928#step:5:752) - setup-envtest trying to download release artifacts). This is a relatively new change in GitHub, see https://www.stepsecurity.io/blog/harden-runner-detects-new-traffic-to-release-assets-githubusercontent-com-across-multiple-customers.
* CI
```release-note
```

chore: add release-assets.githubusercontent.com to allowed-endpoints

---

pkg/providers/imagefamily/bootstrap/aksbootstrap.go
pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go
pkg/providers/instancetype/suite_test.go

Fixes # 
This change propagates the following missing flags to node bootsrap vars: 
```
--cpu-manager-policy
--topology-manager-policy
--container-log-max-size
--container-log-max-files
--pod-max-pids
--allowed-unsafe-sysctls
```
* Ran `make test`, every test passed.
* Verified that a selected kubelet flag (allowed-unsafe-sysctls) on a live cluster, the flag worked.
* Added a new unit test `KubeletConfigToMap` function.
```release-note
NONE
```

fix: Propagate missing kubelet flags to node bootstrap variables

---

pkg/controllers/nodeclass/status/images.go
pkg/controllers/nodeclass/status/kubernetesversion.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Fixes # 
Doing some testing surrounding the maintenance window integration, and the nodeclass status controllers in general, had me uncovering multiple ways for improvement, which this PR aims to do.
- manual testing of `make az-all` + inspecting of logs for different cases.
- E2E Runs:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15592313549
- https://github.com/Azure/karpenter-provider-azure/actions/runs/15594986110 (latest)
```release-note
```

chore(logging): update logging for nodeclass status controllers

---

pkg/operator/operator.go
pkg/providers/instance/azure_client.go

When the process launches, if it doesn't check that it can retrieve a token, then if it's unable to retrieve a token later it will continue to retry getting a token, but won't ever exit the process.
This is a problem especially in the managed NAP case, because there's an IMDS proxy that needs to be set up before the NAP pod can get a token, but if the Karpenter pod starts too quickly it will open a connection in the transport connection pool to the wrong address (not the proxy), which will never serve it the correct token. This will mostly self-recover if request load is low, because the transport idle timeout will be hit and a new connection will go to the proxy, but if request load is high enough it can keep the connection open forever.
Better to lose the race gracefully and just exit …

fix: issue where container can come up but be unable to access token

---

pkg/auth/auxiliarytoken.go
pkg/cloudprovider/suite_test.go
pkg/controllers/nodeclaim/garbagecollection/suite_test.go
pkg/fake/auxiliarytokenserver.go
pkg/fake/auxiliarytokenserver_test.go
pkg/fake/virtualmachinesapi.go
pkg/providers/imagefamily/nodeimage_test.go
pkg/providers/imagefamily/suite_test.go
pkg/providers/instance/azure_client.go
pkg/providers/instance/suite_test.go
pkg/providers/instancetype/suite_test.go
pkg/test/environment.go
pkg/test/nodeclass.go
pkg/test/options.go

* Follow-up from #540 and #910 
* AuxialiaryTokenPolicy will now call a function before every call made by the VM Client
* This function call aux token server if the token is expired or will expire soon. Otherwise, it will use a cached token
* acceptance tests (WIP)
* further e2e testing will be done w/ a test image used by managed Karpenter
```release-note
```

fix: auxiliary token refresh and use sig in acceptance tests

---

pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/instancetypes.go
pkg/providers/instancetype/suite_test.go
test/suites/nodeclaim/eph_osdisk_test.go

Follow-up to #940 
Check whether SKU supports ephemeral disk. Fixes regression in provisioning of selected SKUs that don't support ephemeral OS disk, but might have cache or temp disk that is larger than OS disk (such as Standard_D8pls_v5) - a combination that would cause attempted use of ephemeral OS disk and fail the provisioning.
* Add the check for ephemeral disk support
* Use the same exact logic for ephemeral OS disk size requirement population
* Drop outdated restriction on `Dlds_v5` (which was likely in place due to lack of placement support); tested
* Update unit tests & add E2E tests
There are some additional refactoring, SKU codegen, and cleanup of comments possible and desirable; keeping changes in this PR to the minimum to focus on fixing the regression and …

fix: don't use ephemeral disk if not supported

---

Makefile
hack/release/common.sh
pkg/auth/util.go

Correctly set the user agent on release (and add -aks suffix in CCP images); fixes missing user agent.
* For release & snapshot, set operator.Version in hack/release/common.sh instead of via Makefile
* LDFLAGS/CFLAGS in Makefile are still used for local builds, but aren't passed into snapshot/release targets
* Release scripts still respect CFLAGS if ever passed; augment them with their own version of ldflags
* Use different (-aks) user agent for CCP image
* Remove -aks from "karpenter-aks/v" in favor of suffix in the version itself
* `make snapshot` & examine sigs.k8s.io/karpenter/pkg/operator.Version in the executable
```release-note
```

chore: set user agent on release

---

pkg/providers/instance/azureresourcemanagerutils.go

Fixes # 
NIC not being found from `GET` returns `NotFound` rather than `ResourceNotFound`.
Seems like an issue for `azure-sdk-for-go-extensions`, if we have not been misusing it(?).
```
// IsNotFoundErr is used to determine if we are failing to find a resource within azure.
func IsNotFoundErr(err error) bool {
azErr := IsResponseError(err)
return azErr != nil && azErr.ErrorCode == ResourceNotFound
}
```
But `deleteVirtualMachineIfExists()` right below this code already takes this matter into our own hands.
The same problem exists for NIC, in which this the same solution could be applied.
```release-note
* Fix an issue where NIC "NotFound" during deletion is considered an …
```

fix: NIC error filter catches "ResourceNotFound", but not "NotFound"

---

test/suites/integration/subnet_test.go

Fixes # 
Now that we pin NAP e2e runs to a particular branch we can change this since v1.5.x will support the nsg provider.
*
```release-note
```

fix: NAP supports nsg provider now, so we can run the nsg provider check in NAP

---

.github/workflows/ci-test.yml

Fixes # 
I constantly end up re-running ci-test due to flake, if it fails in one version it fails it for all tests. That is annoying and often makes deflaking this take a couple additional runs, lets not use fail-fast and try this for a bit. 
The tests are so flakey it was very easy to reproduce this 
This shows this change works! And decreases the number of tests we have to rerun :) 
*
```release-note
```

chore: add fail-fast false to CI-TEST action

---

pkg/providers/instance/instance.go
pkg/providers/instance/resperrorhandlers.go

Contributes to #833
Remove unnecessary logging in places where error is returned and would be logged later (e.g. by controller) 
Viewing logs through `make az-debug` and VSCodes Kubernetes extension.
```release-note
Removed and restructured redundant provider layer logs.
```

chore: remove redundant logging in provider layer

---

charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
pkg/apis/v1alpha2/aksnodeclass.go
pkg/apis/v1alpha2/crd_validation_cel_test.go

Add CEL validation for the tags field of AKSNodeClass
* Unit tests
```release-note
AKSNodeClass spec.tags field is now validated and will reject invalid tag configurations.
```

fix: validate ARM tags in AKSNodeClass

---

test/pkg/environment/azure/environment.go

The existing assertions failed to work because the Makefile does Foo=${Foo}, which unconditionally sets the Foo variable even if the result is an empty string.
* Manually
```release-note
NONE
```

fix: Tests should panic if env is not setup right

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/suite_test.go
pkg/controllers/nodeclaim/garbagecollection/suite_test.go

It used the wrong tag key so would never get the InstanceType details
```release-note
NONE
```

fix: bug with CloudProvider list where it never used correct tags key

---

pkg/providers/instancetype/suite_test.go
pkg/providers/launchtemplate/launchtemplate.go

Fixes # 
1.34 introduces a new pattern with how we target daemonsets for different CNI modes.  This adds a pr to add labels for the new feature
- make test
- e2e run: https://github.com/Azure/karpenter-provider-azure/actions/runs/16953512983
```release-note
```

feat: support stateless cni in 1.34+

---

go.mod
go.sum
hack/code/instancetype_testdata_gen/main.go
hack/code/locations_gen/main.go
hack/codegen.sh
pkg/fake/locations.json
pkg/fake/subscriptionsapi.go
pkg/operator/operator.go
pkg/providers/instance/azure_client.go
pkg/providers/instancetype/instancetypes.go
pkg/providers/zone/zone.go
pkg/providers/zone/zone_test.go
pkg/test/environment.go

Calls the list subscriptions API and dynamically determines if a region is zonal or not
Fixes #826.
* Unit tests
* E2E tests: https://github.com/Azure/karpenter-provider-azure/actions/runs/17003024324
```release-note
source region zonal information from API, with fallback to hardcoded list if API is unavailable.
```

feat: add zone provider

---

pkg/auth/config.go
pkg/fake/resourceskuapi.go
pkg/providers/instance/azure_client.go
pkg/providers/instance/skuclient/skuclient.go
pkg/providers/instancetype/instancetypes.go
pkg/providers/instancetype/suite_test.go
pkg/test/environment.go

Now that we're using the Track2 SDK for authentication, we don't need to periodically refresh the client.
We know this is true because other clients using the same credential do not hit issues with token refresh. Additionally if we examine the ServicePrincipal credential we can see that it does support refresh:
[ClientSecretCredential](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/client_secret_credential.go#L73) calls [GetToken()](https://github.com/Azure/azure-sdk-for-go/blob/f0871996d2bc4f9ebb97fb94cb00285f8df8437d/sdk/azidentity/confidential_client.go#L104) which calls [AcquireTokenSilent](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/main/apps/confidential/confidential.go#L589) which handles refresh/expiry at [this …

chore: clean up skuclient

---

go.mod
go.sum

Upstream release notes: https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.6.2
E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/17308808178 - looks good.
```release-note
Update to sigs.k8s.io/karpenter v1.6.2 from 1.6.1
```

chore: update Karpenter core dependency to 1.6.2

---

Makefile-az.mk

* Allow VM size to be overridden as sometimes the default VM size is not available.
* Allow ACR suffix to be overridden, as non-public clouds have a different ACR suffix.
```release-note
NONE
```

chore: update Makefile to more easily support non-public clouds

---

pkg/controllers/nodeclaim/inplaceupdate/controller.go
pkg/providers/instance/instance.go
pkg/providers/instance/suite_test.go

There are currently cases where a node can join the cluster successfully but not have the billing extension installed. This blocks identity propagation and tags propagation.
We tolerate a missing billing extension since this is currently possible.
* Unit test
```release-note
NONE
```

fix: Don't block PATCH VM if billing extension is not installed
