Azure/karpenter-provider-azure

- .github/workflows/e2e-matrix-trigger.yaml
Fixes # 
This change still isn't working as desired. Reverting until we can get this working as expected.
 
This is a reversion to a previously working state.
*
```release-note
NONE
```
> test(e2e): turn off ApprovalComment trigger for now

- pkg/providers/instance/instance.go
- pkg/providers/instancetype/suite_test.go
Respect `topology.kubernetes.io/zone` NodePool requirement, if specified
```release-note
```
> fix: respect NodePool zone requirement (if any)

- pkg/utils/opts/armopts.go
Fixes # 
*
```release-note
```
> chore: removing unused var

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
Fixes # 
Removing unused code
```release-note
```
> chore: remove provisional image drift implementation

- .github/workflows/build-publish-mcr.yml
- .github/workflows/ci-test.yml
- .github/workflows/deflake.yml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
Follow-up to https://github.com/Azure/karpenter-provider-azure/pull/110, adding missing permissions
* Manual trigger on updated Actions
```release-note
```
> fix: add missing job permissions

- go.mod
- go.sum
Fixes # 
Upgrading our karpenter dep to the current newest `v0.33.x` patch version released:
- https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.33.2
`make presubmit`, and `/test`
*
```release-note
NONE
```
> chore(karpenter dep): upgrade karpenter dep v0.33.0 -> v0.33.2

- pkg/apis/v1alpha2/labels.go
- pkg/providers/instancetype/suite_test.go
Remove SKU selection labels that are unused
```release-note
```
> chore: remove unused SKU selection labels

- pkg/cache/cache.go
- pkg/cache/unavailableofferings.go
- pkg/providers/instancetype/instancetypes.go
Fixes #226 
Introduces improved caching for fully initialized instance types. Please see #226 for details, this PR implements everything on the list there.
* make presubmit
* perf before/after - using CP method duration metric for GetInstanceTypes
```release-note
Improved performance and memory footprint via instance type caching
```
> perf: instance types cache

- .devcontainer/devcontainer.json
- go.mod
- go.sum
Fixes # 
CI Is currently broken everywhere due to security vuln. Adding this to fix that see: https://github.com/Azure/karpenter-provider-azure/actions/runs/8559691187/job/23456977053
make ci-non-test
```release-note
```
> chore: bumping go to 1.22

- hack/release/common.sh
Fixes # 
Noticed the released helm chart was missing a `/controller` within its image reference making it fail to pull. Fixing.
*
```release-note
NONE
```
> chore(release): update calculation of image repo for MCR

- go.mod
- go.sum
Update upstream Karpenter to v0.36.1
https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.36.1
```release-note
```
> deps: bump upstream Karpenter to v0.36.1

- hack/deploy/configure-values.sh
- karpenter-values-template.yaml
Fixes https://github.com/Azure/karpenter-provider-azure/issues/300
Updates `karpenter-values-template.yaml` and `configure-values.sh` to propagate kubelet identity into node identities
* TBD
```release-note
```
> fix: propagate kubelet identity into node identities

- pkg/providers/instancetype/suite_test.go
Fixes # 
The parsemap function had some bugs in it where depending on the ordering it would fail. Lets opt in for the simpler solution until the azure cni without overlay kubelet flags handlers get in which are much better tested. 
This PR fixes the CI for 1.30.
K8S_VERSION="1.30.x" make test
```release-note
```
> ci: fixing 1.30 tests

- karpenter-values-template.yaml
Fixes # 
There is a typographical error in the helm values template file.
Nothing to test, it's on a comment.
*
```release-note
NONE
```
> fix: Typographical error on karpenter-values-template.yaml

- README.md
Update version in readme to reflect the latest release
> docs(readme): update version to 0.5.1

- .github/workflows/e2e-matrix-trigger.yaml
Fixes # 
Removing the CommentApproval workflow run option for now. Switching to manual trigger case. Will look at more improvements for dev flow as a follow up.
Nothing Additional
*
```release-note
NONE
```
> test(e2e): remove comment approval trigger

- .github/workflows/release-trigger.yaml
Constrains top-level permissions for release-trigger
*
```release-note
```
> Set top-level permissions to `contents: read`

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
- hack/toolchain.sh
Fixes # 
This is being used in toolchain (for 1.25 CI pipeline only). Need to add it to allow list.
* CI
```release-note
NONE
```
> ci: add dl.k8s.io to egress policy allowlist for toolchain

- hack/deploy/configure-values.sh
Reverts Azure/karpenter-provider-azure#530
> Revert "Replace VNET_SUBNET_ID source in configure-values.sh."

- charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
- pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
Regenerate CRDs
```release-note
```
> fix: update CRDs

- README.md
Fixes # 
Updating the readme for self-hosted install using helm.
Ran through the steps myself in a free environment.
*
```release-note
NONE
```
> docs(self-hosted): Update Readme

- docs/workshops/10_multi_node_consolidation.md
- docs/workshops/1_install_karpenter.md
- docs/workshops/2_basic_nodepool.md
- docs/workshops/6_drift.md
- docs/workshops/9_single_node_consolidation.md
- docs/workshops/kubecon_azure_cheat_sheet.md
- docs/workshops/kubecon_azure_track.md
- docs/workshops/reestablish_env.md
Fixes # 
Creating a set of docs for adapting KubeCon docs for Azure.
I ran through all the steps and tested the entire workshop documented in this PR (didn't test aks-node-viewer)
*
```release-note
NONE
```
> docs(workshop): KubeCon Azure workshop docs

- docs/workshops/1_aks_cluster_creation_and_install_karpenter.md
- docs/workshops/kubecon_azure_track.md
Fixes # 
Adding a re-establish command for getting the env vars back for MSI, and cluster creation
Testing in cloud shell
*
```release-note
NONE
```
> docs(workshop): add re-establish command

- charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
- pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
This PR regenerates CRDs with the latest `controller-gen` pulled in by toolchain (which now uses `@latest` instead of specific version).
```release-note
```
> chore: regenerate CRDs with the latest controller-gen

- README.md
minor doc update
```release-note
```
> docs: updating limitations

- pkg/controllers/nodeclaim/garbagecollection/suite_test.go
- pkg/providers/instance/instance.go
Follow-up for #642
We decided to merge in the network interface gc work and prepare a cherry-pick for it, but there were a couple of suggested comments remaining in that pr. This pr solves some of those comments. 
```release-note
```
> refactor: network interface garbage collection followup

- go.mod
Bump go minor version to 1.23.6
* N/A
```release-note
```
> chore: bump go minor version to 1.23.6

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- hack/validation/labels.sh
- hack/validation/requirements.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Duplicate missing validation rules from v1 into v1beta1 API
```release-note
```
> fix(API): add missing validation rules for v1beta1

- Makefile-az.mk
Don't require access to Graph for role assignments
Manually
```release-note
```
> chore: Don't require access to Graph for role assignments

- Makefile-az.mk
- hack/deploy/create-cluster.sh
> chore: Further authentication fixes (missed in #685)

- go.mod
Bump Go version to fix vulnerability
> chore: bump Go mod version

- pkg/providers/instance/instance.go
> chore: basic reformatting

- pkg/providers/instancetype/instancetypes.go
Fixes #731 
Updated list of zonal regions from https://learn.microsoft.com/en-us/azure/reliability/regions-list#azure-regions-list-1 and EUAP regions. Also verified no updates in sov cloud regions. Automations could be a follow-up.
*
```release-note
* Updated list of zonal regions as of 20250423
```
> chore: update static list of zonal regions

- test/suites/integration/repair_policy_test.go
Fixes # 
*
```release-note
```
> fix: testing duration in e2e

- pkg/providers/pricing/pricing.go
Fix panic on logging after context cancellation
* Successful CI w/o manual re-run, repeated x4 ✅
```release-note
```
> test: fix logging after cancel

- pkg/operator/operator.go
Can be used to access the kube-apiserver in the cluster where the Karpenter pod is running, for cases where the Karpenter pod is running in a different cluster than it is managing.
* UT and manually ran utilization E2E locally.
- [x No
```release-note
NONE
```
> chore: add InClusterClient in operator.go

- pkg/providers/instance/instance.go
Fixes #784 
Previously, the tag changes from AKSNodeClass was not applied to the CSExtension's tags. 
This PR adds those tags to the CSExtensions' tags.
* Test Added to check CSExtension's tags drifted from the AKSNodeClass
```NONE
```
> fix: Adding tags to the CSExtension and BillingExtension

- pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
Switch artifact streaming on. (Will need to be revisited when support for Azure Linux v3 and Ubuntu 24.04 is added.)
* E2E: will be tested elsewhere, as self-hosted does not exercise bootstrap client
```release-note
```
> feat: switch artifact streaming on

- pkg/utils/gpu.go
Update the versions of GPU drivers
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/15006556766 ✅
```release-note
```
> chore: bump GPU driver versions

- cmd/controller/main.go
- cmd/controller/main_ccp.go
- pkg/operator/options/options.go
* Manually
```release-note
NONE
```
> chore: Log initial options configuration (useful for debugging)

- hack/release/common.sh
Block republishing images with the same tag
* Attempted to `make snapshot` (same tag) twice, second attempt failed
```release-note
```
> feat: on publishing images, check if tag already exists

- pkg/operator/options/options.go
- pkg/operator/options/options_validation.go
- pkg/operator/options/suite_test.go
- pkg/providers/instance/instance.go
- pkg/providers/instance/suite_test.go
- pkg/test/options.go
Adds support for `--linux-admin-username` option (`LINUX_ADMIN_USERNAME` environment variable)
```release-note
```
> feat: support `--linux-admin-username` option

- .ko.yaml
Change base image to Azure Linux 3
* `make az-run`
* E2E: https://github.com/Azure/karpenter-provider-azure/actions/runs/15309841523 ✅
```release-note
```
> chore: change base image to Azure Linux 3

- go.mod
- pkg/test/azure/tracker.go
- test/pkg/environment/azure/environment.go
- test/pkg/environment/azure/expectations.go
- test/pkg/environment/azure/setup.go
This ensures that if tests create Azure resources, they are deleted.
* Manually
```release-note
NONE
```
> chore: Add Azure resource tracker

- go.mod
Fixes # 
CI pipeline started flagging an issue, which is fixed in `1.24.4`, so bumping the go version:
https://github.com/Azure/karpenter-provider-azure/actions/runs/15593286375/job/43917455540
```release-note
Updating patch version of go to `v1.24.4`
```
> chore(go.mod): update go version 1.24.4

- .devcontainer/devcontainer.json
Fixes several issues with outdated or broken devcontainer features
* Rebuilding devcontainer
```release-note
```
> fix: update devcontainer features

- pkg/consts/consts.go
- pkg/fake/nodebootstrappingapi_test.go
- pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap_test.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/instance/instance.go
Fixes # 
Change from using string literals to constants.
```release-note
```
> chore: make storageprofile values constants

- pkg/providers/instance/instance.go
Fixes # 
We don't want to consider cloudprovider.Delete() a failure on cases where VM deletion succeeded, but not NIC deletion. NIC garbage collector will be responsible for cleaning up those cases anyway.
This will make `karpenter_cloudprovider_errors_total` more practical by excluding these "safe" errors.
```release-note
NONE
```
> fix: make returning error on NIC deletion failure on cleanup optional

- README.md
> docs: clarify README for Self-Hosted vs NAP

- go.mod
- go.sum
Bump sig.k8s.io/karpenter to [v1.6.1](https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.6.1) (the only change is cherry picking of "fix: rate limit eviction when PDBs are blocking")
```release-note
```
> chore: bump sig.k8s.io/karpenter to v1.6.1

- .gitignore
> fix: add .out files to gitignore

- charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
- pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
- pkg/apis/v1beta1/aksnodeclass.go
- pkg/apis/v1beta1/crd_validation_cel_test.go
> fix: add missing v1beta1 AKSNodeClass tags validation

- pkg/providers/imagefamily/azlinux.go
- pkg/providers/imagefamily/azlinux3.go
- pkg/providers/imagefamily/azlinux3_test.go
- pkg/providers/imagefamily/azlinux_test.go
- pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
- pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap_test.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/imagefamily/ubuntu_2004.go
- pkg/providers/imagefamily/ubuntu_2004_test.go
- pkg/providers/imagefamily/ubuntu_2204.go
- pkg/providers/imagefamily/ubuntu_2204_test.go
- pkg/provisionclients/models/enums.go
> feat(fips): update ubuntu2004 bootstrappingclient

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/drift.go
- pkg/controllers/nodeclaim/inplaceupdate/controller.go
- pkg/utils/errors.go
- pkg/utils/nodeclaim/nodeclaim.go
- pkg/utils/utils.go
> chore: Small nodeclaim utils refactor

- .github/dependabot.yaml
- charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
- pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
> chore: patch both devcontainer deps

- go.mod
Fixes # 
CVE fix
- check-in pipelines
```release-note
NONE
```
> chore(go): bump go version to 1.24.6

- pkg/cache/unavailableofferings.go
- pkg/logging/keys.go
- pkg/logging/values.go
- pkg/metrics/values.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/instance/instance.go
Fixes # 
Follow up to this PR:
https://github.com/Azure/karpenter-provider-azure/pull/1129
As discussed with @matthchr creating a logging package to contain common logging const values for reuse, and insurance of reused values cross logs 
- E2E Runs:
- https://github.com/Azure/karpenter-provider-azure/actions/runs/17337118093
- https://github.com/Azure/karpenter-provider-azure/actions/runs/17337160358
```release-note
NONE
```
> chore(logging): add logging const pkg with beginning structure and examples
